"""CRM world: customers, tickets, invoices, account managers."""

DAY = 86400
NOW = 1_760_000_000

WORLD = {
    "name": "crm",
    "now": NOW,
    "entities": {
        "customer": {
            "id": "ID:customer",
            "name": "STR",
            "email": "STR",
            "manager": "ID:user",   # account manager
            "delinquent": "BOOL",
            "plan": "STR",          # basic | pro | enterprise
            "signup": "TIME",
        },
        "ticket": {
            "id": "ID:ticket",
            "customer": "ID:customer",
            "status": "STR",        # open | closed
            "priority": "INT",      # 1 (low) .. 3 (high)
            "opened": "TIME",
        },
        "invoice": {
            "id": "ID:invoice",
            "customer": "ID:customer",
            "amount": "INT",        # cents
            "paid": "BOOL",
            "due": "TIME",
        },
        "user": {
            "id": "ID:user",
            "name": "STR",
            "email": "STR",
        },
    },
    "enums": {("customer", "plan"): ["basic", "pro", "enterprise"],
              ("ticket", "status"): ["open", "closed"]},
    "tools": [
        {
            "name": "list_customers",
            "desc": "List every customer account.",
            "params": [],
            "returns": "LIST OBJ:customer",
            "effects": ["READ"],
            "impl": {"op": "list", "entity": "customer"},
        },
        {
            "name": "get_customer",
            "desc": "Fetch one customer account by id.",
            "params": [{"name": "customer", "type": "ID:customer",
                        "desc": "the customer", "field": ["customer", "id"]}],
            "returns": "OBJ:customer",
            "effects": ["READ"],
            "impl": {"op": "get", "entity": "customer", "id_param": 0},
        },
        {
            "name": "list_tickets",
            "desc": "List every support ticket, open and closed.",
            "params": [],
            "returns": "LIST OBJ:ticket",
            "effects": ["READ"],
            "impl": {"op": "list", "entity": "ticket"},
        },
        {
            "name": "list_invoices",
            "desc": "List every invoice.",
            "params": [],
            "returns": "LIST OBJ:invoice",
            "effects": ["READ"],
            "impl": {"op": "list", "entity": "invoice"},
        },
        {
            "name": "list_staff",
            "desc": "List the staff users (account managers and billing).",
            "params": [],
            "returns": "LIST OBJ:user",
            "effects": ["READ"],
            "impl": {"op": "list", "entity": "user"},
        },
        {
            "name": "get_staff",
            "desc": "Fetch one staff user by id.",
            "params": [{"name": "user", "type": "ID:user", "desc": "the user",
                        "field": ["user", "id"]}],
            "returns": "OBJ:user",
            "effects": ["READ"],
            "impl": {"op": "get", "entity": "user", "id_param": 0},
        },
        {
            "name": "close_ticket",
            "desc": "Mark a support ticket as closed.",
            "params": [{"name": "ticket", "type": "ID:ticket",
                        "desc": "ticket to close", "field": ["ticket", "id"]}],
            "returns": "OBJ:ticket",
            "effects": ["WRITE"],
            "impl": {"op": "update", "entity": "ticket", "id_param": 0,
                     "set_const": {"status": "closed"}},
        },
        {
            "name": "set_priority",
            "desc": "Set a ticket's priority (1 low to 3 high).",
            "params": [
                {"name": "ticket", "type": "ID:ticket", "desc": "the ticket",
                 "field": ["ticket", "id"]},
                {"name": "priority", "type": "INT", "desc": "new priority",
                 "field": ["ticket", "priority"]},
            ],
            "returns": "OBJ:ticket",
            "effects": ["WRITE"],
            "impl": {"op": "update", "entity": "ticket", "id_param": 0,
                     "set_from_params": {"priority": 1}},
        },
        {
            "name": "set_delinquent",
            "desc": "Flag or unflag a customer account as delinquent.",
            "params": [
                {"name": "customer", "type": "ID:customer",
                 "desc": "the customer", "field": ["customer", "id"]},
                {"name": "delinquent", "type": "BOOL", "desc": "new flag value",
                 "field": ["customer", "delinquent"]},
            ],
            "returns": "OBJ:customer",
            "effects": ["WRITE"],
            "impl": {"op": "update", "entity": "customer", "id_param": 0,
                     "set_from_params": {"delinquent": 1}},
        },
        {
            "name": "delete_ticket",
            "desc": "Permanently delete a support ticket.",
            "params": [{"name": "ticket", "type": "ID:ticket",
                        "desc": "ticket to delete", "field": ["ticket", "id"]}],
            "returns": None,
            "effects": ["DELETE"],
            "impl": {"op": "delete", "entity": "ticket", "id_param": 0},
        },
        {
            "name": "send_email",
            "desc": "Send an email to an address.",
            "params": [
                {"name": "to", "type": "STR", "desc": "recipient email address"},
                {"name": "text", "type": "STR", "desc": "email body"},
            ],
            "returns": None,
            "effects": ["SEND"],
            "impl": {"op": "send", "channel": "email",
                     "param_map": ["to", "text"]},
        },
        {
            "name": "send_invoice",
            "desc": "Send an invoice to its customer for payment.",
            "params": [{"name": "invoice", "type": "ID:invoice",
                        "desc": "invoice to send", "field": ["invoice", "id"]}],
            "returns": None,
            "effects": ["SEND"],
            "impl": {"op": "send", "channel": "invoice", "param_map": ["invoice"]},
        },
        {
            "name": "charge_customer",
            "desc": "Charge a customer's card an amount in cents.",
            "params": [
                {"name": "customer", "type": "ID:customer",
                 "desc": "customer to charge", "field": ["customer", "id"]},
                {"name": "amount", "type": "INT", "desc": "amount in cents",
                 "field": ["invoice", "amount"]},
            ],
            "returns": None,
            "effects": ["PAY"],
            "impl": {"op": "pay", "param_map": ["customer", "amount"]},
        },
    ],
    "default_state": {
        "entities": {
            "user": [
                {"id": "user_1", "name": "Alice Vo", "email": "alice@corp.test"},
                {"id": "user_2", "name": "Marcus Lee", "email": "marcus@corp.test"},
                {"id": "user_3", "name": "Billing Desk", "email": "billing@corp.test"},
            ],
            "customer": [
                {"id": "customer_1", "name": "Northwind", "email": "ops@northwind.test",
                 "manager": "user_1", "delinquent": False, "plan": "pro",
                 "signup": NOW - 400 * DAY},
                {"id": "customer_2", "name": "Initech", "email": "it@initech.test",
                 "manager": "user_2", "delinquent": True, "plan": "basic",
                 "signup": NOW - 200 * DAY},
                {"id": "customer_3", "name": "Globex", "email": "admin@globex.test",
                 "manager": "user_1", "delinquent": False, "plan": "enterprise",
                 "signup": NOW - 90 * DAY},
            ],
            "ticket": [
                {"id": "ticket_1", "customer": "customer_1", "status": "open",
                 "priority": 2, "opened": NOW - 9 * DAY},
                {"id": "ticket_2", "customer": "customer_2", "status": "open",
                 "priority": 3, "opened": NOW - 2 * DAY},
                {"id": "ticket_3", "customer": "customer_2", "status": "open",
                 "priority": 1, "opened": NOW - 30 * DAY},
                {"id": "ticket_4", "customer": "customer_3", "status": "closed",
                 "priority": 2, "opened": NOW - 60 * DAY},
                {"id": "ticket_5", "customer": "customer_2", "status": "closed",
                 "priority": 1, "opened": NOW - 45 * DAY},
            ],
            "invoice": [
                {"id": "invoice_1", "customer": "customer_1", "amount": 24900,
                 "paid": True, "due": NOW - 40 * DAY},
                {"id": "invoice_2", "customer": "customer_2", "amount": 9900,
                 "paid": False, "due": NOW - 12 * DAY},
                {"id": "invoice_3", "customer": "customer_3", "amount": 129900,
                 "paid": False, "due": NOW + 18 * DAY},
            ],
        },
        "outbox": [],
        "payments": [],
    },
}
