"""Kanban board world: cards and users."""

DAY = 86400
NOW = 1_760_000_000  # default 'now' anchor for this world's default state

WORLD = {
    "name": "kanban",
    "now": NOW,
    "entities": {
        "card": {
            "id": "ID:card",
            "title": "STR",
            "status": "STR",       # todo | doing | done
            "assignee": "ID:user",
            "due": "TIME",
            "urgent": "BOOL",
            "archived": "BOOL",
            "created": "TIME",
        },
        "user": {
            "id": "ID:user",
            "name": "STR",
            "email": "STR",
        },
    },
    "enums": {("card", "status"): ["todo", "doing", "done"]},
    "tools": [
        {
            "name": "list_cards",
            "desc": "List every card on the board, archived ones included.",
            "params": [],
            "returns": "LIST OBJ:card",
            "effects": ["READ"],
            "impl": {"op": "list", "entity": "card"},
        },
        {
            "name": "get_card",
            "desc": "Fetch a single card by its id.",
            "params": [{"name": "card", "type": "ID:card",
                        "desc": "the card to fetch", "field": ["card", "id"]}],
            "returns": "OBJ:card",
            "effects": ["READ"],
            "impl": {"op": "get", "entity": "card", "id_param": 0},
        },
        {
            "name": "create_card",
            "desc": "Create a new card with a title, a due date, and an assignee.",
            "params": [
                {"name": "title", "type": "STR", "desc": "card title",
                 "field": ["card", "title"]},
                {"name": "due", "type": "TIME", "desc": "due date",
                 "field": ["card", "due"]},
                {"name": "assignee", "type": "ID:user",
                 "desc": "user the card is assigned to",
                 "field": ["card", "assignee"]},
            ],
            "returns": "OBJ:card",
            "effects": ["WRITE"],
            "impl": {"op": "create", "entity": "card",
                     "param_fields": ["title", "due", "assignee"],
                     "defaults": {"status": "todo", "urgent": False,
                                  "archived": False, "created": "$now"}},
        },
        {
            "name": "set_status",
            "desc": "Set a card's workflow status (todo, doing, or done).",
            "params": [
                {"name": "card", "type": "ID:card", "desc": "the card",
                 "field": ["card", "id"]},
                {"name": "status", "type": "STR", "desc": "new status",
                 "field": ["card", "status"]},
            ],
            "returns": "OBJ:card",
            "effects": ["WRITE"],
            "impl": {"op": "update", "entity": "card", "id_param": 0,
                     "set_from_params": {"status": 1}},
        },
        {
            "name": "archive_card",
            "desc": "Archive a card so it no longer shows on the board.",
            "params": [{"name": "card", "type": "ID:card",
                        "desc": "card to archive", "field": ["card", "id"]}],
            "returns": "OBJ:card",
            "effects": ["WRITE"],
            "impl": {"op": "update", "entity": "card", "id_param": 0,
                     "set_const": {"archived": True}},
        },
        {
            "name": "assign_card",
            "desc": "Assign a card to a user.",
            "params": [
                {"name": "card", "type": "ID:card", "desc": "the card",
                 "field": ["card", "id"]},
                {"name": "user", "type": "ID:user", "desc": "new assignee",
                 "field": ["card", "assignee"]},
            ],
            "returns": "OBJ:card",
            "effects": ["WRITE"],
            "impl": {"op": "update", "entity": "card", "id_param": 0,
                     "set_from_params": {"assignee": 1}},
        },
        {
            "name": "delete_card",
            "desc": "Permanently delete a card. This cannot be undone.",
            "params": [{"name": "card", "type": "ID:card",
                        "desc": "card to delete", "field": ["card", "id"]}],
            "returns": None,
            "effects": ["DELETE"],
            "impl": {"op": "delete", "entity": "card", "id_param": 0},
        },
        {
            "name": "list_users",
            "desc": "List every user on the board.",
            "params": [],
            "returns": "LIST OBJ:user",
            "effects": ["READ"],
            "impl": {"op": "list", "entity": "user"},
        },
        {
            "name": "get_user",
            "desc": "Fetch a single user by id.",
            "params": [{"name": "user", "type": "ID:user", "desc": "the user",
                        "field": ["user", "id"]}],
            "returns": "OBJ:user",
            "effects": ["READ"],
            "impl": {"op": "get", "entity": "user", "id_param": 0},
        },
        {
            "name": "send_message",
            "desc": "Send a direct message to a user.",
            "params": [
                {"name": "user", "type": "ID:user", "desc": "recipient",
                 "field": ["user", "id"]},
                {"name": "text", "type": "STR", "desc": "message text"},
            ],
            "returns": None,
            "effects": ["SEND"],
            "impl": {"op": "send", "channel": "message",
                     "param_map": ["to", "text"]},
        },
    ],
    "default_state": {
        "entities": {
            "user": [
                {"id": "user_1", "name": "Bob", "email": "bob@acme.test"},
                {"id": "user_2", "name": "Dana", "email": "dana@acme.test"},
                {"id": "user_3", "name": "Priya", "email": "priya@acme.test"},
            ],
            "card": [
                {"id": "card_1", "title": "Fix login bug", "status": "doing",
                 "assignee": "user_1", "due": NOW - 3 * DAY, "urgent": False,
                 "archived": False, "created": NOW - 20 * DAY},
                {"id": "card_2", "title": "Write Q3 report", "status": "todo",
                 "assignee": "user_2", "due": NOW + 5 * DAY, "urgent": False,
                 "archived": False, "created": NOW - 10 * DAY},
                {"id": "card_3", "title": "Renew TLS cert", "status": "todo",
                 "assignee": "user_1", "due": NOW - 1 * DAY, "urgent": True,
                 "archived": False, "created": NOW - 15 * DAY},
                {"id": "card_4", "title": "Update onboarding doc",
                 "status": "done", "assignee": "user_3", "due": NOW - 8 * DAY,
                 "urgent": False, "archived": False,
                 "created": NOW - 30 * DAY},
                {"id": "card_5", "title": "Plan offsite", "status": "done",
                 "assignee": "user_2", "due": NOW + 12 * DAY, "urgent": False,
                 "archived": True, "created": NOW - 40 * DAY},
                {"id": "card_6", "title": "Migrate database", "status": "doing",
                 "assignee": "user_3", "due": NOW - 6 * DAY, "urgent": True,
                 "archived": False, "created": NOW - 25 * DAY},
            ],
        },
        "outbox": [],
        "payments": [],
    },
}
